---
driver:
  name: vagrant
  vm_hostname: zimbra.test.lan
  customize:
    memory: 1024
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["private_network", {ip: "192.168.188.33"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[modularit-zimbra::default]
    attributes:
